### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by ramess101** [ramess101/JCED_FOMMS_Manuscript#1]
- [ ] Include bootstrapped uncertainties from MBAR:
    - [ ] When comparing MBAR and HR
    - [ ]  When plotting the optimal epsilon-scaling factor

- [ ] Analyze generalized Potoff and TraPPE for branched alkanes

- [ ] Obtain branched alkane data

- [ ] Basis function results
     - [ ] Validation
     - [ ] 2-D scan for CH3 and CH2
     - [ ] 2-D scan for CH2 of cyclohexane with TraPPE as reference

**Comment by ramess101** [comment]
- [ ] Simulate n-hexane, isobutane, neopentane, and isooctane with:

    - [ ] TraPPE rerun with Potoff
    - [ ] TraPPE rerun with NERD
    - [ ] Potoff rerun with TraPPE
    - [ ] Potoff rerun with Potoff SL
